### PR TITLE
Fit and Finish Refactor

### PR DESCRIPTION
**Pull request by ryanwilliamson01**
PR includes two previous PRs before those get merged.

- General UI refactors across most components. 
- Elimination fo most bootstrap components and replaced by Angular Material/Angular Flex layout. 
- Refactor of table to support better date formatting and use the Material components. 
- Transition of the detail view to a bottom sheet with a new layout. 
- Dynamic sizing in most components depending on screen size.

### CODE REVIEW

**Comment by shankari** [comment]
Would it be possible to add a map to the detail screen (table on click) showing where the data collection occurred?

**Comment by ryanwilliamson01** [comment]
I think so. Would you want it to be interactive or would a static one be fine?

**Comment by shankari** [comment]
I think static would be fine. It's just that lat/lon has the same problem as timestamps in terms of being user intelligible.
But if you use a leaflet/mapbox map, then you get basic interactivity (zoom + pan) by default, no?
It's actually harder to not have interactivity as I know from personal experience :)

**Comment by ryanwilliamson01** [comment]
Done

**Comment by shankari** [comment]
@ryanwilliamson01 

There are a couple of pending fit and finish issues in my review comments for #40 
Also, can you indicate the commits where this happened:

> Elimination fo most bootstrap components and replaced by Angular Material/Angular Flex layout.

I believe the bootstrap components were mainly in the header/sidebar, and I don't see any changes to those files here.

**Pull request merged**
